### ISSUE TITLE
browser-ext/login make error

### ISSUE THREAD

**Issue by hironemu** [mitro-co/mitro#131]
I encountered the following error.
Does anyone know how to solve this problem?

```
root@07417951b071:/mitro/browser-ext/login# make
kzjs_srouces = ../api/build/node/lib/node_modules/keyczarjs/*.js
forge_srouces = ../api/build/node/lib/node_modules/keyczarjs/node_modules/node-forge/js/*.js
/mitro/browser-ext/login/build/chrome/release/URI.js
Traceback (most recent call last):
  File "./ccache.py", line 137, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./ccache.py", line 132, in main
    subprocess.check_call(args)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
/bin/sh: 1: exit: Illegal number: common/URI.js
make: *** [/mitro/browser-ext/login/build/chrome/release/URI.js] Error 2
```

I installed on Ubuntu 14.04 on Docker.
Install steps:
```
# install require packages
apt-get update && apt-get install -y git-core curl python build-essential

# install node & npm
curl -sL https://deb.nodesource.com/setup | bash -
apt-get install -y nodejs

# install mitro

git clone https://github.com/mitro-co/mitro \
&& cd /mitro/browser-ext/api \
&& ./build.sh

cd /mitro/browser-ext/login
make <<<<<<< error
```

**Comment by hironemu** [comment]
I have solved this problem by installing JDK.

```
# apt-get install openjdk-7-jdk
```
